# Generated by Django 6.0.4 on 2026-05-05 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='P.O. Number')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.CharField(max_length=150)),
                ('diseno', models.CharField(max_length=150, verbose_name='Nombre del Diseño')),
                ('dimensiones', models.CharField(max_length=100, verbose_name='Size (Width x Length)')),
                ('tipo', models.CharField(choices=[('MANO', 'A Mano'), ('MAQUINA', 'A Máquina')], max_length=10)),
                ('layout_img', models.ImageField(blank=True, null=True, upload_to='layouts/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstruccionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField(verbose_name='Fecha del Correo')),
                ('texto_instruccion', models.TextField(verbose_name='Texto de la Instrucción')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrucciones', to='jdtextiles_app.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('BODEGA', 'Bodega'), ('TINERIA', 'Tiñería'), ('PREPARACION', 'Preparación'), ('TELAR', 'Telar/Tejido'), ('TERMINADOS', 'Terminados'), ('GERENCIA', 'Gerencia')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('BODEGA', 'Bodega'), ('TINERIA', 'Tiñería'), ('PREPARACION', 'Preparación'), ('TELAR', 'Telar/Tejido'), ('TERMINADOS', 'Terminados'), ('GERENCIA', 'Gerencia')], max_length=20)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado')], default='EN_PROCESO', max_length=20)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='jdtextiles_app.ordentrabajo')),
            ],
        ),
    ]
