# Generated by Django 6.0.4 on 2026-06-08 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='P.O. Number')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.CharField(max_length=150)),
                ('diseno', models.CharField(max_length=150, verbose_name='Nombre del Diseño')),
                ('ancho_ft', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ancho (FT)')),
                ('ancho_in', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ancho (IN)')),
                ('largo_ft', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Largo (FT)')),
                ('largo_in', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Largo (IN)')),
                ('tipo', models.CharField(choices=[('MANO', 'A Mano'), ('MAQUINA', 'A Máquina')], max_length=10)),
                ('layout_img', models.ImageField(blank=True, null=True, upload_to='layouts/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstruccionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField(verbose_name='Fecha del Correo')),
                ('instrucciones_clave', models.TextField(verbose_name='Instrucciones Específicas')),
                ('cuerpo_correo', models.TextField(blank=True, null=True, verbose_name='Cuerpo Completo del Correo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrucciones', to='jdtextiles_app.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='CalculoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('MANO', 'A Mano (Hand)'), ('MAQUINA', 'A Máquina (Machine)')], max_length=15)),
                ('sq_ft', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='SQ.F.')),
                ('hilos_por_pulgada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hilos x Plg')),
                ('peine', models.CharField(blank=True, max_length=50, null=True, verbose_name='Peine')),
                ('por_diente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Por Diente')),
                ('largo_urdir', models.CharField(blank=True, max_length=50, null=True, verbose_name='Largo Urdir')),
                ('material_pie', models.TextField(blank=True, null=True, verbose_name='Detalle Material en PIE')),
                ('material_trama', models.TextField(blank=True, null=True, verbose_name='Detalle Material en TRAMA')),
                ('somet_yardas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yardas SOMET')),
                ('material_somet', models.TextField(blank=True, null=True, verbose_name='Detalle Hilos SOMET')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('material_dornier', models.TextField(blank=True, null=True, verbose_name='Detalle DORNIER JSON')),
                ('dornier_metros_urdir', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dornier_metros_lineales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculo', to='jdtextiles_app.ordentrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('CALCULO', 'Cálculo de Material'), ('BODEGA', 'Bodega'), ('TINERIA', 'Tiñería'), ('PREPARACION', 'Preparación'), ('TELAR', 'Telar/Tejido'), ('TERMINADOS', 'Terminados'), ('GERENCIA', 'Gerencia')], max_length=20)),
                ('rol_calculo', models.CharField(choices=[('MANO', 'Calculista Telar Manual'), ('MAQUINA', 'Calculista Máquina (Somet/Dornier)'), ('JEFE', 'Jefe / Administrador (Ve todo)')], default='JEFE', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('CALCULO', 'Cálculo de Material'), ('BODEGA', 'Bodega'), ('TINERIA', 'Tiñería'), ('PREPARACION', 'Preparación'), ('TELAR', 'Telar/Tejido'), ('TERMINADOS', 'Terminados'), ('GERENCIA', 'Gerencia')], max_length=20)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado')], default='EN_PROCESO', max_length=20)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='jdtextiles_app.ordentrabajo')),
            ],
        ),
    ]
