# Generated by Django 6.0.4 on 2026-05-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdtextiles_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruccioncorreo',
            name='texto_instruccion',
        ),
        migrations.AddField(
            model_name='instruccioncorreo',
            name='cuerpo_correo',
            field=models.TextField(blank=True, null=True, verbose_name='Cuerpo Completo del Correo'),
        ),
        migrations.AddField(
            model_name='instruccioncorreo',
            name='instrucciones_clave',
            field=models.TextField(default='N/A', verbose_name='Instrucciones Específicas'),
            preserve_default=False,
        ),
    ]
