# Generated by Django 6.0.4 on 2026-05-08 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdtextiles_app', '0002_remove_instruccioncorreo_texto_instruccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='departamento',
            field=models.CharField(choices=[('CALCULO', 'Cálculo de Material'), ('BODEGA', 'Bodega'), ('TINERIA', 'Tiñería'), ('PREPARACION', 'Preparación'), ('TELAR', 'Telar/Tejido'), ('TERMINADOS', 'Terminados'), ('GERENCIA', 'Gerencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trackingproduccion',
            name='departamento',
            field=models.CharField(choices=[('CALCULO', 'Cálculo de Material'), ('BODEGA', 'Bodega'), ('TINERIA', 'Tiñería'), ('PREPARACION', 'Preparación'), ('TELAR', 'Telar/Tejido'), ('TERMINADOS', 'Terminados'), ('GERENCIA', 'Gerencia')], max_length=20),
        ),
        migrations.CreateModel(
            name='CalculoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('MANO', 'A Mano (Hand)'), ('MAQUINA', 'A Máquina (Machine)')], max_length=15)),
                ('sq_ft', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='SQ.F.')),
                ('hilos_por_pulgada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hilos x Plg')),
                ('peine', models.CharField(blank=True, max_length=50, null=True, verbose_name='Peine')),
                ('por_diente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Por Diente')),
                ('material_pie', models.TextField(verbose_name='Detalle Material en PIE')),
                ('material_trama', models.TextField(verbose_name='Detalle Material en TRAMA')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculo', to='jdtextiles_app.ordentrabajo')),
            ],
        ),
    ]
