# Generated by Django 6.0.4 on 2026-06-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdtextiles_app', '0003_alter_perfilusuario_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='dimensiones',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='ancho_ft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ancho (FT)'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='ancho_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ancho (IN)'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='largo_ft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Largo (FT)'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='largo_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Largo (IN)'),
        ),
    ]
