# Generated by Django 6.0.4 on 2026-06-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdtextiles_app', '0004_remove_ordentrabajo_dimensiones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculomaterial',
            name='largo_urdir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Largo Urdir'),
        ),
        migrations.AddField(
            model_name='calculomaterial',
            name='material_somet',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle Hilos SOMET'),
        ),
        migrations.AddField(
            model_name='calculomaterial',
            name='somet_yardas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yardas SOMET'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rol_calculo',
            field=models.CharField(choices=[('MANO', 'Calculista Telar Manual'), ('MAQUINA', 'Calculista Máquina (Somet/Dornier)'), ('JEFE', 'Jefe / Administrador (Ve todo)')], default='JEFE', max_length=20),
        ),
        migrations.AlterField(
            model_name='calculomaterial',
            name='material_pie',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle Material en PIE'),
        ),
        migrations.AlterField(
            model_name='calculomaterial',
            name='material_trama',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle Material en TRAMA'),
        ),
    ]
