# Generated by Django 6.0.4 on 2026-06-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdtextiles_app', '0005_calculomaterial_largo_urdir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculomaterial',
            name='material_dornier',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle DORNIER JSON'),
        ),
    ]
