# Generated by Django 6.0.4 on 2026-06-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdtextiles_app', '0006_calculomaterial_material_dornier'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculomaterial',
            name='dornier_metros_lineales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calculomaterial',
            name='dornier_metros_urdir',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
